databricks/databricks-sql-nodejs

.github/workflows/main.yml
package.json

Tweak NPM (some improvements)

---

lib/index.ts

As per this issue https://github.com/databricks/databricks-sql-nodejs/issues/44
This is a small change, but I have run these anyway and no issues:
```sh
npm run type-check
npm run prettier:check
npm run test
```
I didn't run the E2E but there's no logic changes here, just exposing the type.

Export the DBSQLSession

---

lib/DBSQLClient.ts
lib/DBSQLOperation.ts
lib/contracts/IOperation.ts
tests/e2e/batched_fetch.test.js

Data fetching currently relies on functionality from HiveUtils class and is too low-level for end user. This PR moves fetch use-case into the operation class and enables users to fetch by chunk in cases where they need to conserve memory.

Peco 219 - Enable chunked fetch

---

CONTRIBUTING.md
README.md
package.json
tests/e2e/.mocharc.js
tests/unit/.mocharc.js

`npm test`/`npm run e2e` without arguments will run all the tests; if one (or multiple) files passed - only them will be used. See updated README for examples.
Also, fixed a typo about e2e config location.

Ability to specify tests to run

---

lib/connection/connections/HttpConnection.ts
tests/unit/connection/connections/HttpConnection.test.js

Currently connections using `https: false` still attempt to use the `https.Agent`. This causes thrift to throw an error. This PR uses the plain `http.Agent` in the case `https: false` in order to fix this.
<details>
<summary>Code + Error</summary>
```javascript
const client = new DBSQLClient();
const conn = await client.connect({
host: "redacted",
path: "redacted",
// other options
https: false,
ssl: false,
headers: {'X-redacted': 'true'},
});
const sess = await conn.openSession();
const queryOp = await sess.executeStatement('SELECT "Hello, World!"', { runAsync: true });
const result = await queryOperation.fetchAll();
console.table(result);
await queryOperation.close();
await sess.close();
await conn.close();
```
```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. …
```

Support http agent for non https connections

---

lib/DBSQLOperation/OperationStatusHelper.ts
tests/unit/DBSQLOperation.test.js

Internal ticket number: [PECO-319]
Fixes databricks/databricks-sql-nodejs#58
When cluster is stopped, attempt to run any operation against it will initiate cluster start, and the operation will enter a `PENDING_STATE` state. Previously this state for some reason was considered an error, but in fact once cluster is up, operation moves on and is executed properly.
https://github.com/databricks/databricks-sql-nodejs/commit/8f8c5c6f53ff24c54eea14dcfbf8320720362088 contains the actual fix
https://github.com/databricks/databricks-sql-nodejs/commit/e50054d283a6fd856c26ef724df560c76c8325c8 is a minor improvement that adds some delay between requests for operation status

[PECO-319] Pending status should not be considered error

---

lib/DBSQLSession.ts
lib/contracts/IDBSQLSession.ts
tests/unit/DBSQLSession.test.js

databricks/databricks-sql-nodejs#51 follow-up
Enable Direct results support for all operations that could use it.
In databricks/databricks-sql-nodejs#51, direct results support was implemented in IDBSQLOperation class, and ability to use it (through option `maxRows`) was added to IDBSQLSession.executeStatement.
This PR adds the same `maxRows` option to other methods of IDBSQLSession which allows to use direct results feature with them as well. _Note:_ not all the methods of IDBSQLSession support direct results; option was added only where it was possible.
Easier to review commit by commit:
- https://github.com/databricks/databricks-sql-nodejs/pull/63/commits/4d358fc7a8b09c4eb9b41400ea64229dae2a9dba contains actual changes
- next few commits are tests refactoring
- …

[PECO-237] Direct results support for all operations

---

CHANGELOG.md
lib/DBSQLClient.ts
lib/contracts/IDBSQLClient.ts
tests/e2e/batched_fetch.test.js
tests/e2e/data_types.test.js
tests/unit/DBSQLClient.test.js

List of changes:
1. hide thrift details and expose only usable options (https://github.com/databricks/databricks-sql-nodejs/commit/0eb6634c81dee8614a7fbbd2ae1be0e78da5d7d5)
2. expose initial namespace config (https://github.com/databricks/databricks-sql-nodejs/commit/3b0b978980e0a4ebbd668c97778fdf42d4f2cc72)
3. use `client_protocol_i64` instead of `client_protocol` in order to enable Thrift protocol versions above `SPARK_CLI_SERVICE_PROTOCOL_V2` (https://github.com/databricks/databricks-sql-nodejs/commit/3b91837bed4394531d868c18245abdddb2d4d078)

[PECO-217] DBSQLClient.openSession refactoring

---

lib/DBSQLOperation/index.ts

We were using the spread operator improperly: it copies in all args of the array into the callstack, which will crash the callstack if the array is too big.

Fixed bug with spread operator crashing memory if chunk is too big

---

lib/DBSQLSession.ts
lib/contracts/IDBSQLSession.ts

Previously only `executeStatement` supported this option. But I think it may be useful to have it for other operations as well (e.g. `getTables` or `getColumns` may return quite a lot of records, so it may be handy to be able to run them asynchronously).

[PECO-217] Expose runAsync option for operations that support it

---

lib/DBSQLSession.ts
lib/contracts/IDBSQLSession.ts

Part of [PECO-217]
Removing `TExecuteStatementReq.confOverlay` options as it is deprecated:

Remove deprecated option `confOverlay`

---

tests/e2e/data_types.test.js

Something recently has changed, and now default comment value is `null` and not empty string

Fix e2e tests

---

CHANGELOG.md
lib/DBSQLOperation/index.ts
lib/DBSQLSession.ts
lib/contracts/IDBSQLSession.ts
lib/contracts/IOperation.ts
tests/e2e/batched_fetch.test.js
tests/unit/DBSQLSession.test.js

Previously user had to explicitly pass `maxRows` to use direct results feature. Now if `maxRows` is omitted, it will default to `100000 ` (same value we use for `fetchChunk`/`fetchAll` defaults), and to disable direct results `maxRows` should be explicitly set to `null` (e.g. for use with `runAsync`)

[PECO-348] Enable direct results by default

---

tests/unit/utils.test.js

User agent string has a whitespace between version and comment part. While library version had a suffix - that whitespace was captured into it. But after we tagged non-beta version - it started to fail. The solution is to explicitly "eat" that whitespace

Fix mistake in test

---

examples/logging.js
lib/DBSQLLogger.ts
lib/contracts/IDBSQLLogger.ts
tests/unit/DBSQLOperation.test.js
tests/unit/DBSQLSession.test.js

To clarify, bug was that LogLevel was being cast to a string and interpreted as filepath (String is a superset of LogLevel).

Fixed bug in Logger, cleaned up types

---

CHANGELOG.md
lib/result/JsonResult.ts
tests/unit/result/JsonResult.test.js

Fixes databricks/databricks-sql-nodejs#84
Previously, when processing fetch response and converting it to set of records, library attempted to parse a "real" column name from the name returned by server: it did it by taking part after the last `.` character. This approach is not correct for two reasons:
1. it just doesn't work properly if table contains columns with dots in names (like in the issue mentioned above). In this case the only correct option is to use original name;
2. more generic reason: even if server decided to prepend column name with table name - most likely there was a good reason for this (e.g. resolve names conflict). In this case, obviously, it's better to just take everything as is; if that naming algorithm doesn't work for user - they could always explicitly rename …

[PECO-446] Use original column names when parsing fetch response

---

lib/connection/connections/HttpConnection.ts
lib/index.ts
package-lock.json
package.json
patches/thrift+0.16.0.patch

Nodejs `thrift` package is build in a way that only errors returned in Thrift RPC response message will be passed to an operation's callback. All other errors, e.g. failed request, non-2xx HTTP response, etc. will be just emitted on connection object.
This PR adds a local patch for a `thrift` package which allows to pass HTTP errors to operation callback which later could be handled in `.catch()` handlers. It becomes possible to examine error object and find out why particular operation failed. It could be useful, for example, for re-trying particular request if it failed due to HTTP 5xx error, etc.

Patch `thrift` package so it handles transport errors with a corresponding opertion's callback

---

CHANGELOG.md
package-lock.json
package.json

We've fixed some annoying bugs (and a lot of people are waiting for these fixes), and improved error handling since 1.0.0. So it's time for a next release

Prepare release v1.1.0

---

CHANGELOG.md
package.json

We patched `thrift` dependency in order to improve error handling mechanism. However, that patch wasn't applied when installing connector from NPM. This PR fixes it by publishing patched `thrift` with the library code, and later it will be installed as a local dependency for the connector.
[`bundleDependencies` docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bundledependencies)
<details>
<summary>Example directory structure after installing `@databricks/sql` with this fix as a dependency</summary>
```
├─ package.json
├─ package-lock.json
└─ node_modules
├─ @databricks
│  └─ sql
│     ├─ dist
│     │  ├─ ...
│     └─ node_modules
│        ├─ node-int64
│        ├─ q
│        └─ thrift    // <-- patched library - local for @databricks/sql
│            └─ ...
├─ ...
└─ …
```

Make sure that patch needed for improved error handling is applied when installing package

---

.github/workflows/main.yml
.github/workflows/release.yml

Currently used actions versions are going to be deprecated and should be updated (it's mostly related to Node12 deprecation in favor of Node16)
**Upd:** `tisonkun/actions-dco@1.1` still uses Node12 so there's still a warning for DCO check workflow (tisonkun/actions-dco#12), but ATM we cannot fix this one, so let's proceed with what's fixed so far.

Update actions because currently used ones became deprecated

---

lib/DBSQLClient.ts

For the SQLTools driver for Databricks I want to leverage the auth provider from the VSCode extension. I need to be able to provide a customer auth provider because my tokens expire and I need a way to update them dynamically.
See https://github.com/databricks/sqltools-databricks-driver/pull/60

Make auth provider configurable

---

tests/e2e/arrow.test.js
tests/e2e/batched_fetch.test.js
tests/e2e/data_types.test.js

Until now it worked just by an accident: server doesn't immediately close session, but obviously it's not a correct usage of session

Fix E2E tests: session used after being closed

---

CHANGELOG.md
package-lock.json
package.json
patches/thrift+0.16.0.patch

Update our patch for `thrift` dependency: immediately stop processing respone on HTTP error statuses (non-200), otherwise it leads to weird errors when trying to parse Thrift response body. Related to [ES-662981]
Update to the way we ship patched `thrift` dependency: Yarn 2 and upper does not respect `bundledPackages` field and completely ignores bundled dependencies. Instead, we copy patched `thrift` into `dist/node_modules` explicitly. It works because Nodejs looks in nested `node_modules` first, and only if package not found there - will attempt to go up the directory tree. Dependencies of `thrift` itself will still be located at their default locations since we still depend on `thrift` library and it will be installed as usual.
Also, with the changes mentioned above, we're going to …

Update `thrift` library patch and prepare release

---

lib/connection/connections/HttpConnection.ts
lib/connection/contracts/IConnectionOptions.ts
lib/contracts/IDBSQLClient.ts
lib/globalConfig.ts
patches/thrift+0.16.0.patch
tests/e2e/timeouts.test.js
tests/unit/connection/connections/HttpConnection.test.js

Currently, for all Thrift requests timeouts are not set not handled.As per PECO-742, a single request should not block indefinitely.

[PECO-745] Default request timeout

---

.eslintrc
lib/DBSQLClient.ts
lib/connection/auth/DatabricksOAuth/AuthorizationCode.ts
lib/connection/auth/DatabricksOAuth/OAuthManager.ts
lib/connection/auth/DatabricksOAuth/OAuthScope.ts
lib/connection/auth/DatabricksOAuth/index.ts
lib/contracts/IDBSQLClient.ts
tests/unit/DBSQLClient.test.js
tests/unit/connection/auth/DatabricksOAuth/OAuthManager.test.js
tests/unit/connection/auth/DatabricksOAuth/index.test.js

[PECO-833]
See also databricks/databricks-sql-python#86
[PECO-833]: https://databricks.atlassian.net/browse/PECO-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support OAuth flow for Databricks Azure

---

lib/result/ArrowResult.ts

Right now ArrowResult returns default epoch timestamp `1970-01-01T00:00:00.000Z` when a data type timestamp returns a null value
https://github.com/databricks/databricks-sql-nodejs/blob/0a2bdb47df8fba59c27e981679703c02d04ec132/lib/result/ArrowResult.ts#L104
expected behavior is to return the null value

return null when timestamp value is null instead of epoch default ts

---

.github/workflows/main.yml
lib/DBSQLOperation/FetchResultsHelper.ts
lib/DBSQLOperation/SchemaHelper.ts
lib/DBSQLOperation/index.ts
lib/DBSQLSession.ts
lib/contracts/IDBSQLSession.ts
lib/globalConfig.ts
lib/result/ArrowResult.ts
lib/result/CloudFetchResult.ts
lib/result/IOperationResult.ts
lib/result/JsonResult.ts
package-lock.json
package.json
tests/e2e/arrow.test.js
tests/e2e/cloudfetch.test.js
tests/unit/result/ArrowResult.test.js
tests/unit/result/CloudFetchResult.test.js
tests/unit/result/JsonResult.test.js
tests/unit/result/compatibility.test.js

[PECO-238]
[PECO-238]: https://databricks.atlassian.net/browse/PECO-238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PECO-238] Initial CloudFetch implementation

---

thrift/TCLIService.d.ts
thrift/TCLIService.js
thrift/TCLIService_types.d.ts
thrift/TCLIService_types.js

Ran `thrift -r --gen js:ts,node TCLIService.thrift`

Updated thrift files

---

.github/workflows/main.yml

Follow up on databricks/databricks-sql-nodejs#172
Since we've split unit and e2e jobs, codecov stopped seing the full coverage report. So now we store coverage reports after unit and e2e jobs, and unpack them when running coverage job so it can process both

Fix coverage reporting in CI

---

lib/DBSQLParameter.ts
lib/DBSQLSession.ts
lib/contracts/IDBSQLSession.ts
lib/index.ts
tests/unit/DBSQLParameter.test.js

It's unsafe to allow the user to pick any string. We should instead limit the types that they can set on parameters. We do this via an enum.

[PECO-1052] Added enum type class to DBSQLParameter class

---

lib/connection/auth/DatabricksOAuth/OAuthManager.ts
tests/unit/connection/auth/DatabricksOAuth/OAuthManager.test.js

In OAuth M2M flow, token refresh is not really supported. Instead, each time when access token expires, a new one should be acquired using client secret

[PECO-932] OAuth M2M flow: fix token refresh flow

---

lib/result/ArrowResult.ts
package-lock.json
package.json
tests/unit/result/utils.test.js

Fixes databricks/databricks-sql-nodejs#150

Upgrade `apache-arrow`

---

lib/DBSQLSession.ts

Currently, the server side will not enable parameterized queries unless a flag manually overrides, or the client protocol/server protocol are both v8. However, if it detects a lower version, it won’t return an error; it will just pass an empty set of parameters. We need to add a client side check to ensure more transparency for the user.

[PECO-1080] Added version check that throws on low protocol version

---

CHANGELOG.md
lib/index.ts
package-lock.json
package.json
tests/e2e/query_parameters.test.js
tests/e2e/staging_ingestion.test.js

Prepare release v1.5.0

---

lib/DBSQLSession.ts

It's unclear to some users why their server doesn't support params. I've added the soonest version of DBR that should support them to the error message.

[PECO-1015] Changed error message to tell users which version of DBR will support parameterized queries.

---

lib/DBSQLParameter.ts
tests/e2e/query_parameters.test.js

This PR adds support for inferring NULL values passed to DBR as parameters. Both `null` and `undefined` could be used as `NULL` values. 
Related to databricks/databricks-sql-python#233

Query parameters: implement support for binding NULL parameters

---

lib/DBSQLParameter.ts
lib/DBSQLSession.ts

Follow up on this comment https://github.com/databricks/databricks-sql-nodejs/pull/189#discussion_r1342003976

Refine DBSQLParameter class

---

lib/DBSQLClient.ts
lib/DBSQLOperation/FetchResultsHelper.ts
lib/DBSQLOperation/index.ts
lib/DBSQLSession.ts
lib/connection/auth/DatabricksOAuth/AuthorizationCode.ts
lib/connection/auth/DatabricksOAuth/OAuthManager.ts
lib/connection/auth/DatabricksOAuth/index.ts
lib/connection/auth/PlainHttpAuthentication.ts
lib/contracts/IClientContext.ts
lib/contracts/IDriver.ts
lib/hive/HiveDriver.ts
lib/result/ArrowResult.ts
lib/result/CloudFetchResult.ts
lib/result/JsonResult.ts
tests/e2e/batched_fetch.test.js
tests/unit/DBSQLClient.test.js
tests/unit/DBSQLOperation.test.js
tests/unit/DBSQLSession.test.js
tests/unit/connection/auth/DatabricksOAuth/AuthorizationCode.test.js
tests/unit/connection/auth/DatabricksOAuth/OAuthManager.test.js
tests/unit/connection/auth/PlainHttpAuthentication.test.js
tests/unit/hive/HiveDriver.test.js
tests/unit/result/ArrowResult.test.js
tests/unit/result/CloudFetchResult.test.js
tests/unit/result/JsonResult.test.js
tests/unit/result/compatibility.test.js

This library is designed so we have to initialize a root object (`DBSQLClient`) which later produces many of other object which represent sessions, operations, results sets and so on. And most of those objects require some common stuff, for example - logger, driver, connection - which are created and owned by their parent `DBSQLClient` instance. Previously we were passing those objects separately down the whole tree, and with time it became harder to add new items to that common context. In this PR, common objects are wrapped together into a context provider (implemented by `DBSQLClient`) which is then passed to all classes that need it.
This PR is also a spin-off of databricks/databricks-sql-nodejs#174 (databricks/databricks-sql-nodejs#193) which itself is an example why these changes …

Implement client context

---

lib/DBSQLClient.ts

Fixes databricks/databricks-sql-nodejs#196
When no logger passed to `DBSQLClient`, the default one is created, a new instance per each client. Even though that default logger only prints to console, it still adds some error listeners to process object. And, as reported in databricks/databricks-sql-nodejs#196, if many `DBSQLClient`s created, there will be too many error listeners attached to process. Another possible issue is that since there are no destructors in JS, we cannot properly cleanup logger when client is no longer needed, and we have to rely on GC.
The proposed solution is to use a single default logger instance for all `DBSQLClient` instances. The default logger will be created on demand, so if user doesn't need it - they can pass their own logger to every `DBSQLClient` so …

Make default logger singleton

---

CHANGELOG.md
lib/DBSQLClient.ts
package-lock.json
package.json

Enable `canUseMultipleCatalogs` option when creating session in order to align with other drivers.
Prepare release 1.6.1: update version and changelog.
Easrier to review commit by commit

Enable `canUseMultipleCatalogs` option when creating session

---

lib/DBSQLOperation/index.ts
lib/result/ArrowResultHandler.ts
lib/result/CloudFetchResultHandler.ts
lib/result/IOperationResult.ts
lib/result/IResultsProvider.ts
lib/result/JsonResultHandler.ts
lib/result/RowSetProvider.ts
tests/e2e/arrow.test.js
tests/e2e/cloudfetch.test.js
tests/unit/DBSQLOperation.test.js
tests/unit/result/ArrowResultHandler.test.js
tests/unit/result/CloudFetchResultHandler.test.js
tests/unit/result/JsonResultHandler.test.js
tests/unit/result/compatibility.test.js
tests/unit/result/fixtures/RowSetProviderMock.js

Continuation of databricks/databricks-sql-nodejs#163 and databricks/databricks-sql-nodejs#185
Modify `FetchResultsHelper` and result handlers so they have unified interface and allow chaining. The idea is to form a sort of pipeline that will fetch operation results and then process it on each step. Currently it's just fetching and preparing (converting to array of rows), but later we'll add an additional step to ensure that chunk size matches `maxRows`, or steps that may convert data to different representation (or return raw data)

DBSQLOperation Refactoring (3 of 3)

---

lib/DBSQLOperation/index.ts
lib/connection/connections/HttpConnection.ts

This PR is related to databricks/databricks-sql-nodejs#204. After changes made in that PR, downloading CloudFetch results sometimes started to fail with `ECONNRESET: socket hang up` error. After debugging, I've found a root cause. Even though all the library code is Promise-based, since Promises are microtasks, enqueueing a lot of promises may block macrotasks execution for a while. Usually, there are no much microtasks scheduled. However, when fetching a CloudFetch results, after first set of files are downloaded and being processed immediately one by one (and chunk by chunk), event loop easily gets clogged for enough time to break connection pool. `http.Agent` stops receiving socket events, and marks all sockets invalid on the next attempt to use them. The fix allows to clean up a …

Performance fixes

---

lib/DBSQLSession.ts
tests/e2e/query_parameters.test.js

We don't have any fallback logic for the case when native query parameters are not supported by server (like PySQL for example, which can fallback to inlining parameters), so this protocol version check is basically useless

Remove protocol version check for query parameters

---

lib/result/CloudFetchResultHandler.ts
tests/e2e/cloudfetch.test.js
tests/unit/result/CloudFetchResultHandler.test.js

[PECO-1261]
Previously, CloudFetch result handler enqueued batch of links and waited for all of them to be downloaded; the next batch of links was downloaded only when previous one was read by user.
Now, CloudFetch handler starts downloading links in background, and waits only for the one currently requested by user. More links are enqueued for downloading only on demand, if there are free slots in queue.
Profiler output (result set contains 8 links total, concurrent downloads set to 5). CPU and Event loop graphs clearly show that previously 5 links were fetched, then processed, and then remaining links were fetched and processed. After changes made in this PR, first links are scheduled, and data processing starts once the first one is available while other links continued downloading in …

[PECO-1261] Improve CloudFetch downloading queue

---

CHANGELOG.md
package-lock.json
package.json

All the changes in this release are various fixes. But since they slightly change behavior of `IOperation.fetchChunk()` and `IOperation.hasMoreRows()` I ended up incrementing minor version number instead of build

Prepare release 1.7.0

---

CHANGELOG.md
lib/connection/connections/HttpConnection.ts
package-lock.json
package.json

Fixes databricks/databricks-sql-nodejs#208

Remove limit for sockets per connection to fix "Premature close" error + prepare patch release

---

.github/workflows/main.yml
package.json

Configure CI to run unit tests on different Nodejs versions.
E2e are a somewhat time and resource consuming, so for now they will be executed only once.
It should help with preventing compatibility issues in future (see databricks/databricks-sql-nodejs#219)

CI: run unit tests on multiple Nodejs versions

---

.github/workflows/main.yml
lib/index.ts
lib/polyfills.ts
tests/e2e/arrow.test.js
tests/unit/polyfills.test.js

After upgrading `apache-arrow` in databricks/databricks-sql-nodejs#180 (which was needed to fix databricks/databricks-sql-nodejs#150), this library stopped working in some Nodejs versions. Turns out that `apache-arrow@13` started to massively use `Array.at`/`TypedArray.at` methods which became available only in `Node@16.6.0`.
Even if we forget that `apache-arrow` declares a support for `Node@12` (at least in its `package.json` file), we had two options:
1. stop supporting older Nodejs versions;
2. add polyfills for missing methods.
I ended up implementing own polyfill with this reasoning:
1. we still have users that use Node 16 or even 14 (but for option 1 we'd have to declare support for even newer versions);
2. basically, only one method is currently needed (`Array.at`/`TypedArray.at` …

Add polyfills to make `apache-arrow` work in Node@14

---

lib/DBSQLClient.ts
lib/connection/auth/DatabricksOAuth/OAuthManager.ts
lib/contracts/IDBSQLClient.ts
tests/unit/DBSQLClient.test.js
tests/unit/connection/auth/DatabricksOAuth/OAuthManager.test.js

Add optional property `useDatabricksOAuthInAzure` in the parameter `ConnectionOptions` of `DBSQLClient.connect`. 
If it is set as `true`, it will use Databricks native OAuth rather than Azure AD OAuth in both OAuth U2M and M2M flow. If it is not set or set as `false`, it will still use the existing Azure AD OAuth.
To use this in OAuth M2M flow, the `oauthClientId` and `oauthClientSecret` in the `ConnectionOptions` must be Databricks service principal client ID and secret which can be created by Databricks API or Databricks Account UI.

[PECO-1431] Support Databricks OAuth in Azure

---

lib/connection/auth/DatabricksOAuth/OAuthManager.ts
tests/unit/DBSQLClient.test.js

`useDatabricksOAuthInAzure = true` means that user wants to use Databricks OAuth method on given Azure instance. And if that Azure host is not supported - we shouldn't silently fall back to Azure OAuth but throw an error instead. Azure OAuth should be used only when  `useDatabricksOAuthInAzure = false`

Adjust `useDatabricksOAuthInAzure` behavior

---

lib/DBSQLClient.ts
lib/connection/auth/DatabricksOAuth/OAuthManager.ts
lib/connection/auth/DatabricksOAuth/OAuthScope.ts
lib/connection/auth/DatabricksOAuth/OAuthToken.ts
lib/connection/auth/DatabricksOAuth/index.ts
tests/unit/DBSQLClient.test.js
tests/unit/connection/auth/DatabricksOAuth/OAuthManager.test.js
tests/unit/connection/auth/DatabricksOAuth/OAuthToken.test.js

Fixes databricks/databricks-sql-nodejs#226
This PR also contains some preparation work/refactoring, and is easier to review commit by commit:
- explicitly define which flow to use (04011e451e8bd27844bc811327157acddc09a623). We still rely on presense of `clientSecret` option, but now this condition is moved all the way up to `DBSQLClient`. `OAuthManager` uses dedicated option to choose which flow to use
- when refreshing token, use the same scope as when getting the one (d587eb2a05b1409eb58967441dcc6ae3bb78f5db). U2M and M2M flows refresh token in a different way (M2M actually just obtains a new token). Previously we hard-coded scopes for M2M refresh, but, since Azure and In-House OAuth need different scopes, instead of adding one more hard-code we save token's scopes when obtaining one, …

Use correct scopes for OAuth U2M and M2M flows

---

lib/connection/connections/HttpConnection.ts
tests/e2e/proxy.test.js

Fixes databricks/databricks-sql-nodejs#237
A proxy agent was configured to use a protocol of proxy itself as a protocol for proxy target. In some cases this causes an unintentional modification of target URLs - see https://github.com/databricks/databricks-sql-nodejs/issues/237#issuecomment-2037248591
I don't actually remember why I used that option, maybe I didn't fully understood its impact.

Fix: proxy agent unintentionally overwrites protocol in URL

---

lib/polyfills.ts

I understand the need for the polyfill, but for various security reasons a few production projects `freeze` the ability to modify the constructors so this basically triggers an assignment even when it's not needed and the `freeze` cause a failure. 
Let me know if there's other considerations that you'd like to take for this

refactor(polyfills): do not raise a Assignment call unless needed.

---

lib/DBSQLSession.ts
tests/e2e/staging_ingestion.test.js

Looks that AWS and Azure have a different behavior of HTTP `DELETE` for non-existing files.
AWS assumes that - since file already doesn't exist - the goal is achieved, and returns HTTP 200.
Azure, on the other hand, is somewhat stricter and check if file exists before deleting it. And if
file doesn't exist - Azure returns HTTP 404.
For us, it's totally okay if file didn't exist before removing. So when we get an HTTP 404 -
just ignore it and report success. This way we can have a uniform library behavior for all clouds

UC Volume ingestion: uniform behavior on SQL `REMOVE`

---

lib/DBSQLOperation.ts
lib/DBSQLSession.ts
lib/contracts/IDBSQLSession.ts
lib/contracts/IOperation.ts

Expose an `id` property on `IDBSQLSession` and `IOperation`.
Previosly we did have a `getId()` method on `DBSQLSession` and `DBSQLOperation`. Of course, users were able to use them from JS code, or by casting objects to `any` in TS, but they still were internal to the library. Now we expose a legal way to access session and operation ID as a part of the public library interface

Expose session and query ID

---

lib/polyfills.ts

Change condition in polyfill. `hasOwnProperty` still returns `true` if property is available but its value is `undefined`. Also, the condition contained typo. Instead, explicitly check if `ArrayConstructor.prototype.at` is a function.

Fix polyfill

---

lib/DBSQLOperation.ts
lib/contracts/IOperation.ts
tests/e2e/iterators.test.ts
tests/unit/.stubs/OperationStub.ts

[PECO-983]
[PECO-983]: https://databricks.atlassian.net/browse/PECO-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PECO-983] Support streaming query results via Node.js streams

---

lib/result/CloudFetchResultHandler.ts

When file encryption is enabled with customer provided keys (SSE-CPK), we must pass the keys in HTTP headers in the fetch request. These headers are provided in the property `httpHeaders` in the `TSparkArrowResultLink`

[PECO-2049] Add custom auth headers into cloud fetch request

---

lib/connection/auth/DatabricksOAuth/OAuthManager.ts

Databricks OAuth is supported on `databricks.azure.cn`

[PECO-2153] Support OAuth on databricks.azure.cn

---

.github/workflows/main.yml

When running unit tests with node v14 got error: ValueError: invalid mode: 'rU'
updating python version used when running unit tests for node version 14. [REF](https://stackoverflow.com/questions/74715990/node-gyp-err-invalid-mode-ru-while-trying-to-load-binding-gyp)

updated py version for node14 testing

---

.github/workflows/main.yml
lib/DBSQLClient.ts
lib/utils/buildUserAgentString.ts
tests/unit/utils/utils.test.ts

Issue reported: While migrating usage logic metric, userAgent tag sometimes emitted tokens. 
This PR removes clientID from userAgent string thus mitigating possibility of such scenarios.
Unit tests modified to verify correct userAgentString is built.

removed clientId from userAgent string

---

examples/repl
lib/DBSQLClient.ts
lib/contracts/IDBSQLClient.ts
lib/utils/buildUserAgentString.ts
tests/unit/utils/utils.test.ts

This PR adds `userAgentHeader` option in connect call, so users can configure the user agent string generated. 
Note: clientId arg in `connect` options is renamed to userAgentHeader. The clientId in `OAuthManager` options exists and corresponds to the Databricks Service Principal clientId.
unit tests

renamed clientId to userAgentHeader in connect args

---

CHANGELOG.md
package-lock.json
package.json

1. Added change-log for latest release
2. bumped up version to 1.10.0

prepare release 1.10.0

---

lib/DBSQLSession.ts
lib/contracts/IDBSQLSession.ts
tests/unit/result/ArrowResultHandler.test.ts
tests/unit/result/CloudFetchResultHandler.test.ts

Added useLZ4Compression in ExecuteStatementOptions, thus making compression configurable. This behavior aligns with other databricks sql drivers
Unit tests

[PECOBLR-306] Make LZ4 compression configurable

---

lib/connection/connections/HttpConnection.ts
tests/unit/connection/connections/HttpConnection.test.ts

Fixes https://github.com/databricks/databricks-sql-nodejs/issues/284

Improve url handling

---

lib/DBSQLClient.ts
lib/DBSQLSession.ts
lib/utils/index.ts
lib/utils/protocolVersion.ts
tests/e2e/protocol_versions.test.ts
tests/unit/DBSQLClient.test.ts
tests/unit/DBSQLSession.test.ts
tests/unit/utils/protocolVersion.test.ts

Add thrift version handling for driver support.
based on protocol features list in runtime thrift server. [Link](based on https://github.com/databricks-eng/runtime-dev/blob/3e59d727aa67cec8add4f53d326467304c62b078/sql/hive-thriftserver/if/TCLIService.thrift#L40) 
unit tests
e2e test

[PECOBLR-314] add thrift protocol version handling

---

lib/DBSQLSession.ts
tests/e2e/arrow.test.ts
tests/e2e/cloudfetch.test.ts
tests/unit/DBSQLSession.test.ts

Disable compression if cloud fetch is enabled.
Reason: 
Transient issue `Error: Error: Invalid stream checksum: A9A9B8E @17257 at Decoder.emit_Error` when running cloud fetch query on sql warehouse
Justification:
Minimal impact(~3% on 500MB) result set.
Unit tests
e2e test

disable compression if cloud fetch is enabled

---

tests/unit/thrift-field-id-validation.test.ts

Ensure thrift field IDs are within range
Test fails when limit is lowered:
```
Violations found:
- TCLIService_types.js: Field ID 1281 exceeds maximum allowed value of 1199
- TCLIService_types.js: Field ID 1282 exceeds maximum allowed value of 1199
- TCLIService_types.js: Field ID 1283 exceeds maximum allowed value of 1199
- TCLIService_types.js: Field ID 1284 exceeds maximum allowed value of 1199
- TCLIService_types.js: Field ID 1285 exceeds maximum allowed value of 1199
- TCLIService_types.js: Field ID 1286 exceeds maximum allowed value of 1199
- TCLIService_types.js: Field ID 1287 exceeds maximum allowed value of 1199
- TCLIService_types.js: Field ID 1288 exceeds maximum allowed value of 1199
- TCLIService_types.js: Field ID 1289 exceeds maximum allowed value of 1199
- …
```

Ensure thrift field IDs are within range
