README.md, package.json
Node js sdk is in preview mode, adding a preview tag:
- added a preview note to the readme file.
- changed the version of the package to be published to npm to be `0.1.7-beta.1` indicating a preview release.
=> add preview tag

.gitattributes, CONTRIBUTING.md, README.md, docs/readme.md, docs/troubleshooting.md, examples/data_types.js, examples/session.js, tests/e2e/data_types.test.js, tests/e2e/utils/config.js, tests/unit/HiveClient.test.js, tests/unit/HiveOperation.test.js, tests/unit/HiveSession.test.js, tests/unit/connection/connections/HttpConnection.test.js, tests/unit/factory/StatusFactory.test.js, tests/unit/hive/HiveDriver.test.js, tests/unit/hive/commands/ExecuteStatementCommand.test.js, tests/unit/utils/WaitUntilReady.test.js
Minor fixes to documentation and test code.
I am also using this opportunity to get myself familiar with the code.
=> Minor fixes to documentation and test code

LICENSE, NOTICE, README.md
- Polishes the README.
- Refine instructions for making a local configuration file when running e2e tests
- Disclose the MIT licence for Hive-Driver, from which this project was forked
=> Update readme and licence file

CODEOWNERS
=> Adds codeowners

README.md, docs/readme.md, docs/troubleshooting.md
- Add badges: Npm version, tests and coverage status
- Remove some irrelevant Thrift-related section from docs
=> Update Readme and docs

.github/workflows/main.yml, .github/workflows/release.yml, .gitignore, package.json, tests/e2e/utils/config.js
Before merging this PR, some additional steps should be completed:
1. Add repository secrets: `E2E_HOST`, `E2E_PATH`, `E2E_ACCESS_TOKEN`. PAT should give access to `hive_metastore.default` for DDL (CREATE/DROP) and DML (SELECT/INSERT/...) operations.
2. Add repository secret with Codecov token: `CODECOV_TOKEN`.
=> [PECO-181] (WIP) Fix CI

.github/workflows/main.yml, tests/e2e/data_types.test.js, tests/e2e/utils/config.js
1. Add a config for catalog and database
2. Use more unique names for test tables
=> Some CI improvements

lib/HiveOperation.ts
fixes https://github.com/databricks/databricks-sql-nodejs/issues/22
=> increase default batch size from 100 to 100.000

lib/connection/connections/HttpConnection.ts, tests/unit/connection/connections/HttpConnection.test.js
fixes https://github.com/databricks/databricks-sql-nodejs/issues/23
=> Implement http keep-alive

.github/workflows/main.yml, README.md
=> Fixes after renaming `master` to `main`

CODEOWNERS
=> Adding myself as a CODEOWNER so I can approve changes

examples/cancel_operation.js
=> Add a query cancelling example

CHANGELOG.md, examples/data_types.js, lib/index.ts, package.json
- Update version in `package.json`
- Update changelog
- Minor fixes to examples and code
=> Prepare to release 0.1.8-beta.2

lib/connection/connections/HttpConnection.ts
Nodejs by default will try to use maximum possible TLS version it supports. This PR makes sure that Nodejs will not use TLS below v1.2
=> Enforce minimum TLS version

lib/DBSQLClient.ts
Errors emitted by Thrift may contain some additional fields with complicated nested structures, and when trying to serialize them another error was triggered ("TypeError: Converting circular structure to JSON").
Solution: log only error message + stacktrace.
Also, this PR slightly modifies 'error' event handler of DBSQLClient: previously re-emitting 'error' event caused unhandled exception appearing in console; but since we already log it using logger - that behavior was no longer needed and therefore is disabled now.
Also see comments to the code for other details.
Related to databricks/databricks-sql-nodejs#87 and databricks/databricks-sql-nodejs#85 (hides original error in both cases)
=> [PECO-444] Fix error logging bug

examples/logging.js
=> Remove access tokens

package-lock.json
```
json5  <1.0.2 || >=2.0.0 <2.2.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix`
node_modules/json5
node_modules/tsconfig-paths/node_modules/json5
1 high severity vulnerability
To address all issues, run:
npm audit fix
```
=> Fix `npm audit` security warning

lib/DBSQLClient.ts, lib/DBSQLOperation/CompleteOperationHelper.ts, lib/DBSQLOperation/FetchResultsHelper.ts, lib/DBSQLOperation/OperationStatusHelper.ts, lib/DBSQLOperation/SchemaHelper.ts, lib/DBSQLOperation/index.ts, lib/DBSQLSession.ts
This PR doesn't modify any logic, it just replaces Promise syntax with equivalent async/await constructions. This is intended to make code more uniform as we're using async/await syntax for all the new code. Also, appropriate access modifiers were added to methods and properties of affected classes
=> [REFACTORING] Convert Promise-based methods to async/await

package-lock.json, package.json
Closes databricks/databricks-sql-nodejs#141
Update `patch-package` dependency due to security vulnerability
=> Update `patch-package` dependency

CHANGELOG.md, package-lock.json, package.json
=> Prepare release 1.3.0

CHANGELOG.md, package-lock.json, package.json
Update package version and changelog
=> Prepare release v1.4.0

lib/DBSQLClient.ts, lib/connection/auth/DatabricksOAuth/OAuthManager.ts, lib/contracts/IDBSQLClient.ts, tests/unit/connection/auth/DatabricksOAuth/OAuthManager.test.js
[PECO-932]
Support [OAuth M2M flow](https://docs.databricks.com/en/dev-tools/auth.html#oauth-machine-to-machine-m2m-authentication)
[PECO-932]: https://databricks.atlassian.net/browse/PECO-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PECO-932] Support OAuth M2M flow

lib/DBSQLSession.ts, lib/contracts/IDBSQLSession.ts, lib/errors/ParameterError.ts, tests/e2e/query_parameters.test.js
This PR finishes off the work on the node side for parameterized queries.
=> [PECO-1056] Add support for ordinal parameters

lib/connection/connections/HttpConnection.ts, lib/connection/connections/HttpRetryPolicy.ts, lib/connection/connections/ThriftHttpConnection.ts, lib/connection/contracts/IConnectionProvider.ts, lib/connection/contracts/IRetryPolicy.ts, lib/errors/RetryError.ts, lib/hive/Commands/BaseCommand.ts, lib/result/CloudFetchResultHandler.ts, tests/unit/hive/commands/BaseCommand.test.js
[PECO-1259]
[PECO-1259]: https://databricks.atlassian.net/browse/PECO-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PECO-1259] Implement retry behavior for CloudFetch

CHANGELOG.md, package-lock.json, package.json
- Update package version and changelog
- Fix `npm audit` warnings
=> Prepare release 1.8.0

CHANGELOG.md, lib/DBSQLOperation.ts, package-lock.json, package.json
Resolve [a high severity `npm audit` warning](https://github.com/databricks/databricks-sql-nodejs/security/dependabot/34) and prepare release:
=> Prepare release 1.8.1

package-lock.json
Fixes https://github.com/databricks/databricks-sql-nodejs/security/dependabot/35
=> Update dependencies to fix security warnings
